[package]
name = "measures"
version = "0.1.0"
edition = "2024"

[dependencies]
alga = "0.9.3"
nalgebra = "0.33.2"
num-traits = "0.2.19"

[dev-dependencies]
criterion = "0.5"
rv = { git = "https://github.com/promised-ai/rv", branch = "release/v0.19.0" }

[[bench]]
name = "normal_benchmarks"
harness = false
